#
# Default AMCL localizer configuration file for outdoors_loc_nav
#
# See https://docs.nav2.org/configuration/packages/configuring-amcl.html
#
# meld /opt/ros/jazzy/share/nav2_bringup/params/nav2_params.yaml ~/robot_ws/src/outdoors_loc_nav/outdoors_loc_nav/params/amcl_params.yaml
#

amcl:
  ros__parameters:
    enable_stamped_cmd_vel: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: -1.0 # use range reported by the sensor
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 1000 # Reduced to optimize performance
    min_particles: 300 # Reduced to optimize performance
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    # Note: We disable tf_broadcast because it conflicts with the Navsat map->odom transform.
    tf_broadcast: false # Broadcasting the map->odom transform is why we use ACML.
    transform_tolerance: 0.5  # delay in transform (tf) data that is tolerable in seconds. Default 1.0
    update_min_a: 0.1 # Radians. Default 0.2=11.5 degrees. Less is better for slow or precise movements.
    update_min_d: 0.1 # Meters. Default 0.25. Less is better for slow-moving robots.
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.1 # Default 0.005. Greater value compensates for short readings, such as small obstacles or reflective surfaces
    scan_topic: scan

# see https://docs.nav2.org/configuration/packages/configuring-map-server.html
map_saver:
  ros__parameters:
    enable_stamped_cmd_vel: true
    save_map_timeout: 5.0 # Default: 2.0
    free_thresh_default: 0.25 # Increasing this means being more strict about what counts as empty space.
    occupied_thresh_default: 0.65 # Occupied space minimum probability threshold value for occupancy grid.
    map_subscribe_transient_local: True # Setting this to true means getting more reliable, complete map data but might take slightly longer.

map_server:
  ros__parameters:
    frame_id: map   
    topic_name: map
    #yaml_filename: "assets/maps/empty_map.yaml"

