navsat_transform:
  ros__parameters:
    frequency: 12.0
    magnetic_declination_radians: 0.0
    yaw_offset: 0.0
    zero_altitude: true
    publish_filtered_gps: true
    broadcast_utm_transform: true
    use_odometry_yaw: false
