navsat_transform:

  ros__parameters:

    # Frequency of the main run loop
    frequency: 12.0

    # If your IMU does not account for magnetic declination, enter the value for your location here. If you don't know it,
    # see http://www.ngdc.noaa.gov/geomag-web/ (make sure to convert the value to radians). This parameter is mandatory.
    magnetic_declination_radians: 0.0730129404 # For lat/long of Childersburg, Alabama, USA

    # Your IMU's yaw, once the magentic_declination_radians value is added to it, should report 0 when facing east. If it
    # doesn't, enter the offset here. Defaults to 0.
    #yaw_offset: 1.570796327  # if IMU reads 0 when facing magnetic north instead of east then set parameter to pi/2
    yaw_offset: 0.0

    # If this is true, the altitude is set to 0 in the output odometry message. Defaults to false.
    # Must be left false to avoid random runaway on all axes
    zero_altitude: true # 2D robots always benefit from zero altitude

    # If this is true, all received odometry data is converted back to a lat/lon and published as a NavSatFix message as
    # /gps/filtered. Defaults to false.
    publish_filtered_gps: true

    # If this is true, the transform world_frame->utm transform is broadcast for use by other nodes. Defaults to false.
    broadcast_cartesian_transform: true

    # If this is true, the node ignores the IMU data and gets its heading from the odometry source (typically the
    # /odometry/filtered topic coming from one of robot_localization's state estimation nodes). BE CAREFUL when using this!
    # The yaw value in your odometry source *must* be world-referenced, e.g., you cannot use your odometry source for yaw
    # if your yaw data is based purely on integrated velocities. Defaults to false.
    # Hint: see if navsat_transform subscribes to /imu/data when "false".
    use_odometry_yaw: false  # must be false if you trust your IMU compass and want to rely on it directly (ignoring odometry)
    #use_odometry_yaw: true # make sure that /odometry/global pose has valid orientation (ignores IMU)

    # Instead of using the first GPS location and IMU-based heading for the local-frame origin, users can specify the
    # origin (datum) using this parameter. The fields in the parameter represent latitude and longitude in decimal degrees,
    # and heading in radians. As navsat_transform_node assumes an ENU standard, a 0 heading corresponds to east.
    datum: [33.199840, -86.299795, 0.0]

    # If true, will retrieve the datum from the 'datum' parameter below, if available. If no 'datum' parameter exists,
    # navsat_transform_node will wait until the user calls the 'datum' service with the SetDatum service message.
    wait_for_datum: false
